name: api-prod

services:
  player:
    image: ghcr.io/gocongress/prizes/player:main
    ports:
      - '${PLAYER_APP_HOST_PORT}:80'
    environment:
      SERVICE_NAME: player
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
