name: api-prod

services:
  admin:
    image: ghcr.io/aga-prizes/admin:main
    ports:
      - '${ADMIN_APP_HOST_PORT}:80'
    environment:
      SERVICE_NAME: admin
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
