name: api-prod

services:
  # Shared db
  postgres:
    image: "docker.io/postgres:17-alpine"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER:-postgres}
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - api-net
  postgres-build-dbs:
    build:
      context: ./build-dbs
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER:-postgres}
      DB_NAMES: ${DB_NAME:-postgres}
      SCHEMA_NAMES: api
    volumes:
      - build-db-data-prod:/var/lib/postgresql/data
    networks:
      - api-net

volumes:
  db-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME_PATH:-../../volumes/prod/db-data}
  build-db-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_BUILD_VOLUME_PATH:-../../volumes/prod/build-db-data}

networks:
  api-net:
    driver: bridge
