name: api-prod

services:
  # Shared db
  postgres:
    image: "docker.io/postgres:17-alpine"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER:-postgres}
    volumes:
      - db-data-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - api-net
  postgres-build-dbs:
    build:
      context: ./build-dbs
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER:-postgres}
      DB_NAMES: ${DB_NAME:-postgres}
      SCHEMA_NAMES: api
    volumes:
      - build-db-data-prod:/var/lib/postgresql/data
    networks:
      - api-net

  postgres-backup-db:
    build:
      context: ./backup-db
    volumes:
      - backup-db-data-prod:/database-backups
    environment:
      - DB_HOST="${DB_HOST:-postgres}"
      - DB_PORT="${POSTGRES_PORT:-5432}"
      - DB_NAME="${DB_NAME:-postgres}"
      - DB_USER="${DB_USER:-postgres}"
      - S3_BUCKET="${S3_BUCKET}"
      - S3_PATH="${S3_PATH}"
      - BACKUP_DIR="${BACKUP_DIR:-/database-backups}"
      - RETENTION_DAYS="${RETENTION_DAYS:-30}"
      - AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
      - AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
      - AWS_REGION="${AWS_REGION}"
    networks:
      - api-net

volumes:
  db-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_VOLUME_PATH:-../../volumes/prod/db-data}
  build-db-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_BUILD_VOLUME_PATH:-../../volumes/prod/build-db-data}
  backup-db-data-prod:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DB_BUILD_VOLUME_PATH:-../../volumes/prod/backup-db-data}

networks:
  api-net:
    driver: bridge
